### ISSUE TITLE
도메인 설계

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/bom-platform#1]

**Comment by pci2676** [comment]
실제 외부 API(Github)를 사용해야하는 부분은 interface로 스펙만 정의하고 가짜 객체(stub)을 이용해서 개발을 진행하도록 한다.

**Comment by NDjust** [comment]
### 도메인 1안


- 리뷰어
   - 미션을 리뷰해주는 역할
   - 리뷰하는 미션들

- 챌린저 
   - 미션에 참여하는 역할
   - 참여하는 미션들

- 리뷰
   - 각 챌린저가 참열한 미션 리뷰

- 미션
   - 챌린저가 참여하는 미션 
   - 리뷰어가 리뷰하는 미션


### 도메인 2안

- 리뷰어
   - 미션을 리뷰해주는 역할
   - 리뷰하는 미션들

- 챌린저 
   - 미션에 참여하는 역할
   - 참여하는 미션들

- 리뷰
   - 각 챌린저가 참열한 미션 리뷰

- 등록된 미션
   - 서버에 등록된 미션
   - 참조용

- 미션
   - 챌린저가 실제 참여 혹은 종료한 미션들
   - 챌린저가 참여하는 미션 
   - 리뷰어가 리뷰하는 미션

**Comment by NDjust** [comment]
피드백 요청 내용

- 도메인 1안, 2안에 있는 미션 관리 부분
