### ISSUE TITLE
패키지 및 모듈 설계 피드백 반영

### ISSUE THREAD

**Issue by NDjust** [Java-Bom/bom-platform#10]
### 모듈

클라이언트 모듈

- 클라이언트 모듈로 빼서 하위로
- slack 모듈 (이너모듈)

Web 모듈

- api, front 각각 관리할지 고민
    - front 스크립트
    - or 디렉토리

common 모듈
- enum & logging 관리

### 패키지

- 도메인별 묶음에 대한 설계
- exception 도메인별로 묶을지 고민

**Comment by Gobukgol** [comment]
### 모듈

클라이언트 모듈
- slack 모듈, github 모듈 (이너모듈)

Web 모듈

- api, front 각각 관리할지 고민
    - front 스크립트
    - or 디렉토리

common 모듈 - 1차 **제거**
- enum & logging 관리

### 패키지

- 도메인별로 묶어서 설계
- exception도 도메인별로 묶기
- SpringApplication 클래스는 com.javabom.bomplatform.web 하위에
