### ISSUE TITLE
클라이언트 인터페이스 설계 - Git

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/bom-platform#11]

**Comment by BangKiHyun** [comment]
https://docs.github.com/en/free-pro-team@latest/rest/reference/git#create-a-reference
여기서 Create a reference 가 branch 생성해주는거같아
https://gist.github.com/potherca/3964930 여기서는 git api사용해서 branch 생성하는 방법 알려주네 ㅎㅎ

**Comment by NDjust** [comment]
- [Repository 목록](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos)
- [PR 목록](https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#list-pull-requests)
- [PR 생성](https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#create-a-pull-request)
     - PR assing 할당 가능 (assignee ->미션 참여자, reviewers -> 리뷰어)
     - 리뷰어 등록 가능한지 더 찾아보기
- [PR 리뷰 요청](https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#request-reviewers-for-a-pull-request)
- [브랜치 목록](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#branches)
- [브랜치 생성](https://docs.github.com/en/free-pro-team@latest/rest/reference/git#create-a-reference)
     - [참고](https://stackoverflow.com/questions/9506181/github-api-create-branch)
- PR 닫기
     - 찾아보기

**Comment by NDjust** [comment]
Github Client 

- https://github-api.kohsuke.org/
