### ISSUE TITLE
API 스펙 설계

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/bom-platform#2]
##### 미션 시작-끝

1. 미션 목록 페이지에 접근한다.
2. 미션 페이지를 하나 선택한다.
3. 미션 시작을 누른다.
   - 리뷰어가 배정된다.
   - 자동으로 깃허브에 브랜치가 생성된다.
4. PR을 생성후 플랫폼에서 리뷰 요청을 클릭한다.
   - 깃허브 PR에 리뷰어와 어사이니를 자동으로 등록해준다.
   - 슬랙으로 알람 메세지를 리뷰어에게 전송한다.
5. 리뷰어는 리뷰를 완료한 후 리뷰 완료 버튼을 클릭하여 챌린저에게 리뷰 알람 메세지를 전송한다.

**Comment by NDjust** [comment]
### [API 스펙]

### 참여자

참여자 등록

- 챌린저 
    - 미션에 참여하는 사람 등록
- 리뷰어 
    - 미션 리뷰해주는 사람 등록


### 미션

- 미션 등록
- 미션 목록 보기
- 미션 자세히 보기
- 미션 시작
    - 미션 리뷰어 지정
    - Git 연동

### 리뷰

- 리뷰(PR) 목록 보기
    - 챌린저 : 리뷰를 요청할 수 있는 목록
    - 리뷰어 : 현재 리뷰를 하고 있는 목록
- 리뷰 요청
    - PR 선택 
    - 이력 관리 & 리뷰어에게 알림
    - slack 연동
- 리뷰 완료
    - slack 연동



- [2020/12/02 수정]

**Comment by NDjust** [comment]
피드백 요청 내용

- 참여자 API 구분 (통합 혹은 분리)
