### ISSUE TITLE
API / 도메인 설계 피드백 반영

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/bom-platform#3]

**Comment by Gobukgol** [comment]
- URL은 복수형으로 reviews/{reviewId}

- 각 Mission, ProgressMission, Review 에 생성 시간 추가하기, BaseTimeEntity 상속하지 않고 구현

- 미션에 MissionStep 필드 추가 고려하기 - 1번 미션에 여러 단계가 있는 것

- findAll() 메소드 쓰지 말고 List<Pageable> 로 페이징 기능 가능하게

- 서비스도 비즈니스 로직을 표현해야한다. 따라서 서비스 메소드명 showDetail 같은 걸로 변경

- 1안 select 쿼리가 2번 나가야하고 (reviewer, challenger) 페이징 같은 경우도 어려워진다. 그래서 2안쓰자

**Comment by BangKiHyun** [comment]
- ProgressMission에 Reviewer 추가할 수 있는 구조
  - ex) MissionReviewer 도메인을 만들어서 OneToMany 관계
- Mission 엔티티에 missionSate 추가
  - 닫혀있는 미션인지 활성화된 미션인지 
- Mission 등록 시 fileUrl: String :arrow_right: missionFile: MultipartFile
