### ISSUE TITLE
모듈 및 패키지 설계

### ISSUE THREAD

**Issue by BangKiHyun** [Java-Bom/bom-platform#4]
패키지 컨셉, 모듈 컨셉 정리

**Comment by NDjust** [comment]
멀티 모듈 참고자료

- https://reflectoring.io/spring-boot-gradle-multi-module/
- https://jojoldu.tistory.com/444
- https://woowabros.github.io/study/2019/07/01/multi-module.html

**Comment by NDjust** [comment]
build.gradle 

- compile 
- implementation
- 차이점 및 적용
